// <auto-generated />
using AkhilD_301057929.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AkhilD_301057929.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AkhilD_301057929.Models.AssignFaculty", b =>
                {
                    b.Property<int>("classId");

                    b.Property<int>("courseCode");

                    b.Property<int>("facultyId");

                    b.HasKey("classId");

                    b.HasIndex("courseCode");

                    b.HasIndex("facultyId");

                    b.ToTable("AssignFaculties");
                });

            modelBuilder.Entity("AkhilD_301057929.Models.Course", b =>
                {
                    b.Property<int>("courseCode")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("courseDepartment");

                    b.Property<string>("courseName");

                    b.Property<string>("coursePre");

                    b.HasKey("courseCode");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("AkhilD_301057929.Models.Faculty", b =>
                {
                    b.Property<int>("facultyId");

                    b.Property<string>("department");

                    b.Property<string>("email");

                    b.Property<int>("ext");

                    b.Property<string>("firstName");

                    b.Property<string>("lastName");

                    b.HasKey("facultyId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("AkhilD_301057929.Models.AssignFaculty", b =>
                {
                    b.HasOne("AkhilD_301057929.Models.Course", "Course")
                        .WithMany("assignFaculties")
                        .HasForeignKey("courseCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AkhilD_301057929.Models.Faculty", "Faculty")
                        .WithMany("assignFaculties")
                        .HasForeignKey("facultyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
